### ISSUE TITLE
Readme notes on input size

### ISSUE THREAD

**Issue by rreusser** [scijs/fourier-transform#1]
Great work! I've been wishing for a nice clean implementation for a long time! One small thing: Is it possible to clarify in the readme whether this works non-power-of-two sizes? It wasn't immediately clear to me from either the readme or the source which sizes are permitted (or if there are restrictions at all). Thanks!

**Comment by dfcreative** [comment]
Yes, definitely. Done.
Probably it also needs clarifying what to do in case if user needs NPOT FFT.

**Comment by dfcreative** [comment]
Elaborated a bit, referenced to ndarray for NPOT case.
Thanks!

**Comment by rreusser** [comment]
Thanks! This is great! At risk of getting off-topic, for complex numbers, I kinda liked mikola's original [ndfft](https://github.com/mikolalysenko/ndfft) implementation without the extra weight of ndarray since it's definitely overkill where a reasonably fast, 1-d always-power-of-two fft is needed (shameless example: [complex-deriv-fornberg](https://github.com/scijs/complex-deriv-fornberg/blob/master/index.js#L220))

Long story short, there are maybe a couple more pieces (complex fft, NPOT) that could be harvested/repurposed from various MIT-licensed sources and cleaned up/made presentable. Thoughts on further directions:

- add non-power-of-two to this module? Maybe harvest bluestein from ndarray-fft if can be converted to real fft?
- add complex workalike module (from combination of dsp.js, ndarray-fft, or ndfft?) which handles 1d POT and NPOT?

Bottom line, there are lots of similar use cases for which ndarray of dsp.js or the other modules may be kinda heavy or otherwise not quite right, so could be useful to enumerate a few more and come up with some nice streamlined implementations like this module.

Just thoughts. Thanks again!

**Comment by dfcreative** [comment]
Yes, I was planning initially to implement FFT of _dsp.js_ for complex numbers, but decided that I had no use-cases for that moment.
Yes, I am down for these implementations. It would be nice, I guess, to combine them under the same simple API:
```js
ft(real, complex?);
ft(npotReal);
```
