### ISSUE TITLE
The output array of fft() is NaN 

### ISSUE THREAD

**Issue by nayfusaurus** [scijs/fourier-transform#8]
I am having issues with the FFT() function, the output im receiving is always NaN, and i cannot figure out why. Any help would be appreciated. I am using ReactNative as such my code snippet is as follows:

```
      let tempx = []
      let tempy = []
      let tempz = []

      for(var i =0;i<1024;i++){
        tempx[i] = parseFloat(arrayx[i])
        tempy[i] = parseFloat(arrayy[i])
        tempz[i] = parseFloat(arrayz[i])
      }

      let spectrumx = ft(tempx);
      let spectrumy = ft(tempy);
      let spectrumz = ft(tempz);
```

**Comment by dy** [comment]
What data do you have in arrayx/arrayy/arrayz?

**Comment by nayfusaurus** [comment]
It is just an array of floating point numbers,

`0.0359129347,0.0210662838,0.001524901,0.0491203144,-0.0335123464,-0.0114817517,0.0042267088,0.0187094938,0.0264636911,-0.0880419463,-0.0225331634,-0.0429347344,0.0097205741,-0.0018036191,0.0004731205,0.0099585755,-0.0418495499,-0.0028233882,0.003489336,-0.001040563,0.0106636444,-0.0489495583,0.0834653601,0.0322840065,-0.0584774874,-0.0180417523,0.004726755,0.0037814039,0.0662536472,0.035758771,-0.0422855616,0.0370641313,0.035399355,-0.0425730981,0.0349180847,-0.0008057673,`

**Comment by nayfusaurus** [comment]
Ah yes, you are correct, the error was my dataset. The last entry was not captured properly. I didn't know that this works, parseFloat(NaN) and the result is still a NaN, thus propagating the error to the fft() function. My apologies for opening an issue, but I appreciate your help. Thank you dy!!
